/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fasttheme_FastTheme */

#ifndef _Included_fasttheme_FastTheme
#define _Included_fasttheme_FastTheme
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fasttheme_FastTheme
 * Method:    startMonitoring
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fasttheme_FastTheme_startMonitoring
  (JNIEnv *, jobject);

/*
 * Class:     fasttheme_FastTheme
 * Method:    stopMonitoring
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fasttheme_FastTheme_stopMonitoring
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
