/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fasttheme_FastTheme */

#ifndef _Included_fasttheme_FastTheme
#define _Included_fasttheme_FastTheme
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fasttheme_FastTheme
 * Method:    startMonitoring
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fasttheme_FastTheme_startMonitoring
  (JNIEnv *, jobject);

/*
 * Class:     fasttheme_FastTheme
 * Method:    stopMonitoring
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fasttheme_FastTheme_stopMonitoring
  (JNIEnv *, jobject);

/*
 * Class:     fasttheme_FastTheme
 * Method:    getWindowHandle
 * Signature: (Ljava/awt/Component;)J
 */
JNIEXPORT jlong JNICALL Java_fasttheme_FastTheme_getWindowHandle
  (JNIEnv *, jclass, jobject);

/*
 * Class:     fasttheme_FastTheme
 * Method:    setWindowTransparency
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_fasttheme_FastTheme_setWindowTransparency
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     fasttheme_FastTheme
 * Method:    setTitleBarColor
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_fasttheme_FastTheme_setTitleBarColor
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     fasttheme_FastTheme
 * Method:    setTitleBarTextColor
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_fasttheme_FastTheme_setTitleBarTextColor
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     fasttheme_FastTheme
 * Method:    setTitleBarDarkMode
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_fasttheme_FastTheme_setTitleBarDarkMode
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     fasttheme_FastTheme
 * Method:    getSystemResolution
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fasttheme_FastTheme_getSystemResolution
  (JNIEnv *, jclass);

/*
 * Class:     fasttheme_FastTheme
 * Method:    getSystemDPI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fasttheme_FastTheme_getSystemDPI
  (JNIEnv *, jclass);

/*
 * Class:     fasttheme_FastTheme
 * Method:    isSystemDarkMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_fasttheme_FastTheme_isSystemDarkMode
  (JNIEnv *, jclass);

/*
 * Class:     fasttheme_FastTheme
 * Method:    getSystemRefreshRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fasttheme_FastTheme_getSystemRefreshRate
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
