<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fasttheme.demo</groupId>
    <artifactId>FastThemeDemo</artifactId>
    <version>0.1.7</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.compilerArgs>--enable-preview</maven.compiler.compilerArgs>
    </properties>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastTheme</artifactId>
            <version>0.1.9</version>
            <exclusions>
                <exclusion>
                    <groupId>com.github.andrestubbe</groupId>
                    <artifactId>fastcore</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastWindow</artifactId>
            <version>0.1.2</version>
        </dependency>

        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>fastanimation</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>fasttween</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastCore</artifactId>
            <version>0.1.1</version>
        </dependency>

        <dependency>
            <groupId>com.github.andrestubbe</groupId>
            <artifactId>FastDisplay</artifactId>
            <version>0.1.1</version>
        </dependency>

        <dependency>
            <groupId>fastdirectx</groupId>
            <artifactId>fastdirectx</artifactId>
            <version>0.1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>fastgraphics</groupId>
            <artifactId>fastgraphics</artifactId>
            <version>0.1.1-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                    <compilerArgs>
                        <arg>--enable-preview</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <mainClass>${exec.mainClass}</mainClass>
                    <commandlineArgs>--enable-native-access=ALL-UNNAMED</commandlineArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
